//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Mart_2024.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaksi
    {
        public int id { get; set; }
        public string no { get; set; }
        public System.DateTime tanggal { get; set; }
        public string nama_kasir { get; set; }
        public long total_bayar { get; set; }
        public int user_id { get; set; }
        public int pelanggan_id { get; set; }
        public int barang_id { get; set; }
    
        public virtual tbl_barang tbl_barang { get; set; }
        public virtual tbl_pelanggan tbl_pelanggan { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
